# Generated by Django 5.2 on 2025-04-02 14:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flag for inappropriate content', verbose_name='Is Flagged'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications Enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20, verbose_name='Theme Preference'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(help_text='The response generated by the bot', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Bot Response'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_message',
            field=models.TextField(help_text='The message sent by the user', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='User Message'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief description about yourself', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
